### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Patouvoodo** [OlivierRebon/Projet-1#1]
Code review:

Ligne 37-38 : un peu douteux comme code. La variable afficheMenu est à vrai et elle n'est jamais changé ensuite. Essayez d'éviter les variables non inutilisés.

Ligne 91 : Compléter le nom de la fonction pour que ce soit AjouterAnimal. C'est plus compréhensible

Ligne 95 : Boucle for trop longue. Il faut penser à appeler une fonction

Ligne 138 : Le break est accepté uniquement pour le premier projet. À l'avenir il faudra trouver une autre solution

Ligne 143 : À quoi sert le return ? La fonction retourne à la fonction appelante de toute façon.

Ligne 163 : Ça n'a pas été demandé dans le dossier fonctionnel. Si c'était testé par un analyste ce serait un bug.

**Comment by OlivierRebon** [comment]
Changement de lignes

37-38 -> 17-18  :  À changer
91 -> 43: Nom changé
95 -> 74: Créé fonction ListePleine pour vérifier si plus que 10 animaux sont inscrits.
138 -> 108
143: Retiré
163: Retiré
